journals = {
    { Title = "Calendar Concerns", Author = "Dad", Text = "I'm worried about the calendar. Its days are numbered." },
    { Title = "Fitness Advice", Author = "Pops", Text = "My wife told me to stop impersonating a flamingo. I had to put my foot down." },
    { Title = "Golf Wisdom", Author = "The Old Man", Text = "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!" },
    { Title = "Musical Notes", Author = "Dad", Text = "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera." },
    { Title = "Construction News", Author = "Grandpa", Text = "I only know 25 letters of the alphabet. I don't know y." },
    { Title = "Skeletal Humor", Author = "Dad", Text = "Why didn't the skeleton climb the mountain? It didn't have the guts." },
    { Title = "Tree Talk", Author = "Pops", Text = "How do trees access the internet? They log in." },
    { Title = "Space Cadets", Author = "Dad", Text = "What do you call a spaceman with a broken car? An astro-not." },
    { Title = "Seafood Diet", Author = "Fisherman Fred", Text = "What do you call a fish wearing a bowtie? Sofishticated." },
    { Title = "Elevator Pitch", Author = "Dad", Text = "I used to be addicted to the hokey pokey, but then I turned myself around." },
    { Title = "Zero Hero", Author = "Math Dad", Text = "What did one say to zero? Nice belt!" },
    { Title = "Scarecrow Job", Author = "Farmer John", Text = "Why did the scarecrow win an award? Because he was outstanding in his field." },
    { Title = "Shoe Issues", Author = "Dad", Text = "I don't trust stairs. They're always up to something." },
    { Title = "Sleepy Time", Author = "Nap Master", Text = "I dreamt I was a muffler last night. I woke up exhausted." },
    { Title = "Color Theory", Author = "Artistic Dad", Text = "What is blue and not very heavy? Light blue." },
    { Title = "Train of Thought", Author = "Conductor Dad", Text = "I asked the train driver how many miles he's done. He said he lost track." },
    { Title = "Banking", Author = "Rich Dad", Text = "Why did the old man fall in the well? Because he couldn't see that well." },
    { Title = "Canine Comedy", Author = "Dog Lover", Text = "What do you call a magic dog? A labracadabrador." },
    { Title = "Cold Front", Author = "Winter Dad", Text = "What does a snowman do when he's mad? He has a meltdown." },
    { Title = "Cheesy Joke", Author = "Chef Dad", Text = "What do you call cheese that isn't yours? Nacho cheese." },
    { Title = "Camping Trip", Author = "Scout Leader", Text = "You can't run through a campsite. You can only ran, because it's past tents." },
    { Title = "Pepper Talk", Author = "Spicy Dad", Text = "What does a nosy pepper do? It gets jalapeño business." },
    { Title = "Fake Noodles", Author = "Italian Dad", Text = "What do you call a fake noodle? An impasta." },
    { Title = "Alligator Aid", Author = "Swamp Dad", Text = "What do you call an alligator in a vest? An investigator." },
    { Title = "Library rules", Author = "Bookworm Dad", Text = "I'm reading a book on anti-gravity. It's impossible to put down." },
    { Title = "Mountain Jokes", Author = "Climber Dad", Text = "What did the left eye say to the right eye? Between you and me, something smells." },
    { Title = "Sweet Tooth", Author = "Candy Man", Text = "Why did the cookie go to the hospital? Because he felt crummy." },
    { Title = "Ocean View", Author = "Sailor Dad", Text = "What did the ocean say to the beach? Nothing, it just waved." },
    { Title = "Lighten Up", Author = "Electrician Dad", Text = "How many tickles does it take to make an octopus laugh? Ten tickles." },
    { Title = "Bear market", Author = "Wild Dad", Text = "What do you call a bear with no teeth? A gummy bear." },
    { Title = "Construction", Author = "Builder Dad", Text = "I watched a documentary about how ships are put together. It was riveting." },
    { Title = "Fruit Salad", Author = "Market Dad", Text = "Why did the banana go to the doctor? He wasn't peeling well." },
    { Title = "Ghostly", Author = "Spooky Dad", Text = "What is a ghost's favorite fruit? Booberries." },
    { Title = "Math Problem", Author = "Prof Dad", Text = "Why was six afraid of seven? Because seven eight nine." },
    { Title = "Heavy Lifting", Author = "Gym Dad", Text = "I wouldn't buy anything with velcro. It's a total rip-off." },
    { Title = "Farm Life", Author = "Rural Dad", Text = "Why did the pony get sent to his room? He wouldn't stop horsing around." },
    { Title = "Time Travels", Author = "Sci-Fi Dad", Text = "What time is it when the clock strikes 13? Time to get a new clock." },
    { Title = "Bird Watching", Author = "Avian Dad", Text = "Why do seagulls fly over the ocean? Because if they flew over the bay, they'd be bagels." },
    { Title = "Wall Street", Author = "Business Dad", Text = "Why did the banker quit his job? He lost interest." },
    { Title = "Musical Fruit", Author = "Band Dad", Text = "What kind of music do mummies listen to? Wrap music." },
    { Title = "Insect Inside", Author = "Bug Dad", Text = "How do you make a butterfly? You throw butter out the window." },
    { Title = "Car trouble", Author = "Mechanic Dad", Text = "What has four wheels and flies? A garbage truck." },
    { Title = "Hat Trick", Author = "Fashion Dad", Text = "What did one hat say to the other? Stay here, I'm going on ahead." },
    { Title = "Bathroom Humor", Author = "Dad", Text = "Why did the toilet paper roll down the hill? To get to the bottom." },
    { Title = "Nutty Joke", Author = "Squirrel Dad", Text = "What do you call a nut chasing another nut? A cashew." },
    { Title = "Sweet Corn", Author = "Farmers Market", Text = "What is a corn's favorite type of music? Pop." },
    { Title = "Frosty", Author = "Snow Dad", Text = "What do you call an old snowman? Water." },
    { Title = "Cat Nap", Author = "Feline Dad", Text = "What do you call a pile of kittens? A meowntain." },
    { Title = "Dino Might", Author = "Paleo Dad", Text = "What do you call a dinosaur that is sleeping? A dino-snore." },
    { Title = "Plate Date", Author = "Dishwasher Dad", Text = "What did one plate say to the other? Lunch is on me." },
    { Title = "Volcano", Author = "Geo Dad", Text = "What did the volcano say to his wife? I lava you." },
    { Title = "Bee Hive", Author = "Honey Dad", Text = "What do you call a bee that can't make up its mind? A maybe." },
    { Title = "Cafe Blues", Author = "Barista Dad", Text = "Why did the coffee file a police report? It got mugged." },
    { Title = "Egg-cellent", Author = "Breakfast Dad", Text = "Why did the egg hide? It was a little chicken." },
    { Title = "Computer Wiz", Author = "Tech Dad", Text = "Why was the computer cold? It left its Windows open." },
    { Title = "Rock On", Author = "Geo Dad", Text = "What do you call a rock that listens to grunge? A shamrock." },
    { Title = "Pirate Life", Author = "Captain Dad", Text = "Why are pirates called pirates? Because they arrrrr." },
    { Title = "Frog Prince", Author = "Pond Dad", Text = "What happens when a frog park illegally? It gets toad away." },
    { Title = "Pencil Down", Author = "Office Dad", Text = "Why did the pencil stink? It was a number 2." },
    { Title = "Librarian", Author = "Quiet Dad", Text = "Why did the librarian get kicked off the plane? It was overbooked." },
    { Title = "Coffee Break", Author = "Barista Dad", Text = "How does a rabbi make coffee? Hebrews it." },
    { Title = "Vampire Diaries", Author = "Goth Dad", Text = "Why does a vampire brush his teeth? To prevent bat breath." },
    { Title = "Space Bar", Author = "Astro Dad", Text = "Why did the astronaut break up with his girlfriend? He needed some space." },
    { Title = "Lemonade", Author = "Citrus Dad", Text = "When life gives you melons, you might be dyslexic." },
    { Title = "Skeleton Key", Author = "Bone Dad", Text = "What is a skeleton's favorite instrument? The trombone." },
    { Title = "Waist Management", Author = "Belt Dad", Text = "What do you call a belt made of watches? A waist of time." },
    { Title = "Belt Loop", Author = "Waist Dad", Text = "What does a clock do when it's hungry? It goes back four seconds." },
    { Title = "Fishing Trip", Author = "River Dad", Text = "Why are fish so smart? Because they live in schools." },
    { Title = "Wall Fly", Author = "House Dad", Text = "What did one wall say to the other? I'll meet you at the corner." },
    { Title = "Swiss Cheese", Author = "Dairy Dad", Text = "I made a website for the local cheese factory. It's nothing fancy, just a few pages of brie." },
    { Title = "Train Track", Author = "Loco Dad", Text = "I heard a rumor about specific butter. It's spreading." },
    { Title = "Cantaloupe", Author = "Fruit Dad", Text = "Why do melons have weddings? Because they cantaloupe." },
    { Title = "Stolen Soap", Author = "Clean Dad", Text = "I was going to tell a joke about soap, but it slipped away." },
    { Title = "Pizza Pie", Author = "Delivery Dad", Text = "Burnt pizza, frozen beer, and a pregnant girl. What do they have in common? Some guy didn't take it out in time." },
    { Title = "Chemistry", Author = "Science Dad", Text = "I told a chemistry joke. There was no reaction." },
    { Title = "History Lesson", Author = "History Dad", Text = "Who invented the Round Table? Sir Cumference." },
    { Title = "Grave Yard", Author = "Dead Dad", Text = "Why are graveyards so noisy? Because of all the coffin." },
    { Title = "Duck Tales", Author = "Quack Dad", Text = "What time do ducks wake up? At the quack of dawn." },
    { Title = "Light Bulb", Author = "Bright Dad", Text = "I gave my handyman a to-do list, but he only finished numbers 1, 3, and 5. It turns out he only does odd jobs." },
    { Title = "Elevator Music", Author = "Lift Dad", Text = "I haven't spoken to my wife in years. I didn't want to interrupt her." },
    { Title = "Invisible Man", Author = "Clear Dad", Text = "The invisible man married the invisible woman. The kids were nothing to look at either." },
    { Title = "Forest Gump", Author = "Woods Dad", Text = "Why did the pine tree get in trouble? Because it was being knotty." },
    { Title = "Cereal Killer", Author = "Breakfast Dad", Text = "What is a grain of salt's favorite movie? The Green Mile." },
    { Title = "Bicycle", Author = "Cyclist Dad", Text = "Why can't a bicycle stand up by itself? It's two tired." },
    { Title = "Holy Water", Author = "Church Dad", Text = "How do you make holy water? You boil the hell out of it." },
    { Title = "Tennis Match", Author = "Sporty Dad", Text = "Why should you never date a tennis player? Because love means nothing to them." },
    { Title = "Spider Web", Author = "Arachnid Dad", Text = "What part of the computer do spiders like? The web-cam." },
    { Title = "T-Rex", Author = "Dino Dad", Text = "Why can't you hear a pterodactyl go to the bathroom? Because the 'P' is silent." },
    { Title = "Elevator", Author = "Lift Dad", Text = "My wife asked me why I'm whispering. I said I didn't want Mark Zuckerberg to hear. She laughed. Alexa laughed. Siri laughed." },
    { Title = "Maths", Author = "Calc Dad", Text = "Parallel lines have so much in common. It's a shame they'll never meet." },
    { Title = "Bank Heist", Author = "Robber Dad", Text = "Why did the man run around his bed? To catch up on his sleep." },
    { Title = "Cowboy", Author = "Western Dad", Text = "What do you call a cowboy who is always sad? A jolly rancher. Wait, no." },
    { Title = "Tomato", Author = "Sauce Dad", Text = "Why did the tomato turn red? Because it saw the salad dressing." },
    { Title = "Football", Author = "Coach Dad", Text = "Why was Cinderella so bad at soccer? She kept running away from the ball." },
    { Title = "Cookie Monster", Author = "Baker Dad", Text = "What kind of keys do kids like? Cookies." },
    { Title = "Vampire", Author = "Drac Dad", Text = "What is a vampire's favorite boat? A blood vessel." },
    { Title = "Ghost", Author = "Spirit Dad", Text = "Why are ghosts bad liars? Because you can see right through them." },
    { Title = "Witch", Author = "Hex Dad", Text = "What do you call a witch who lives at the beach? A sand-witch." },
    { Title = "Skeleton", Author = "Bone Dad", Text = "Why did the skeleton go to the party alone? He had no body to go with." },
    { Title = "Mummy", Author = "Wrap Dad", Text = "Why don't mummies avoid relaxing? They're afraid they'll unwind." },
    { Title = "Dracula", Author = "Count Dad", Text = "What is Dracula's favorite fruit? A nectarine." },
    { Title = "Werewolf", Author = "Howl Dad", Text = "What happened when the werewolf swallowed a clock? He got ticks." },
    { Title = "Zombie", Author = "Undead Dad", Text = "What is a zombie's favorite bean? A human bean." },
    { Title = "Frankenstein", Author = "Monster Dad", Text = "What is a monster's favorite dessert? I-scream." },
    { Title = "Alien", Author = "Space Dad", Text = "What kind of music do planets like? Nep-tunes." },
    { Title = "Dogs", Author = "Pup Dad", Text = "What kind of dog does a magician have? A Labracadabrador." },
    { Title = "Cats", Author = "Kitty Dad", Text = "What is a cat's favorite color? Purr-ple." },
    { Title = "Bears", Author = "Polar Dad", Text = "What do you call a bear with no ears? B." },
    { Title = "Llamas", Author = "Wool Dad", Text = "What do you call a very fast llama? A llamaghini." },
    { Title = "Sheep", Author = "Ewe Dad", Text = "Where do sheep go on vacation? The Baa-hamas." },
    { Title = "Cows", Author = "Moo Dad", Text = "What do you call a cow with no legs? Ground beef." },
    { Title = "Horses", Author = "Neigh Dad", Text = "What do you call a horse that lives next door? A neigh-bor." },
    { Title = "Pigs", Author = "Oink Dad", Text = "What do you call a pig that knows karate? A pork chop." },
    { Title = "Ducks", Author = "Bill Dad", Text = "What do you call a crate of ducks? A box of quackers." }
}
